
import { Inter } from 'next/font/google'
import '../Styles/globals.css'
import Navbar from '../Components/Navbar'
import Footer from '@/Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className=' w-full flex flex-col items-center gap-10'>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </main>
      </body>
    </html>
  )
}
